### ISSUE TITLE
Add metrics integration to istio charms

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-k8s-operator#10]
### Enhancement Proposal

We need to connect all metrics provided by istio to the cos stack.  Istio's core has metrics, but the ingress and waypoint gateways also may provide some metrics.  Istio also provides some [example alert rules](https://github.com/istio/tools/blob/6d537aee69ec7e9da007f311562496f7ac1cb691/perf/stability/alertmanager/prometheusrule.yaml) and maybe other suggestions that we should investigate.  

Dod:
* Investigate what metrics and rules are provided by istio
  * If any metrics are identified that come from waypoint or ingress gateways, create new issues on those repos to capture those metrics
* Integrate the metrics from istio's core to the cos stack

**Comment by dstathis** [comment]
This is done.
